### ISSUE TITLE
Getting error KeyError: 'name'

### ISSUE THREAD

**Issue by Doocter** [ragxxv/Bumpr#2]
KeyError: 'name'

**Comment by ragxxv** [comment]
Do you have Disboard bot's DMs open _from_ the selfbot account?

**Comment by Doocter** [comment]
Yeah, when i DMed from selfbot to disboard, then i able to execute command, you should mention this in readme.md

**Comment by ragxxv** [comment]
https://github.com/ragxxv/Bumpr?tab=readme-ov-file#requirements

It is already mentioned in the requirements, guess I'll edit to make it _more_ clear.
